import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SubNavbar } from "../components/ui/sub-navbar";
import { PageWrapper } from "@/components/ui/page-wrapper";
import { SecondaryNavbar } from "@/components/ui/secondary-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased flex flex-col h-screen bg-background`}
      >
        <SubNavbar />
        <SecondaryNavbar />
        <div className="flex flex-1 overflow-hidden">
          <div className="flex flex-1 overflow-hidden bg-muted/40">
            <PageWrapper>{children}</PageWrapper>
          </div>
        </div>
      </body>
    </html>
  );
}
